// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6w7GY6vd9gWKG75_TZIYrD43TaBs-ws',
    appId: '1:360625992410:web:891da205559b275f7a2be3',
    messagingSenderId: '360625992410',
    projectId: 'wiredsocial-a98d6',
    authDomain: 'wiredsocial-a98d6.firebaseapp.com',
    storageBucket: 'wiredsocial-a98d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0vQs6j3uz7Qdabe1n2jba7na_P4kmnss',
    appId: '1:360625992410:android:9e06656c053dd45f7a2be3',
    messagingSenderId: '360625992410',
    projectId: 'wiredsocial-a98d6',
    storageBucket: 'wiredsocial-a98d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiK_H5R1FaNe9VY2jQ7X4cYlh2a6SNdkk',
    appId: '1:360625992410:ios:2f63d5154696075e7a2be3',
    messagingSenderId: '360625992410',
    projectId: 'wiredsocial-a98d6',
    storageBucket: 'wiredsocial-a98d6.appspot.com',
    iosClientId: '360625992410-qhgphmsmklb0bmmmv8ahn2hv3ecfgeak.apps.googleusercontent.com',
    iosBundleId: 'com.appinventiv.wiredSocial',
  );
}
